package:
  name: pqctio
  version: {{ GIT_DESCRIBE_TAG | lower | replace("v","") }}

source:
  path: ./../../

build:
  number: 0

# Note, boost has an upperbound right now to hanlde cmake correctly
requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.2
    - boost >=1.57,<=1.67
    - ninja
    - gtest
  run:
    - boost >=1.57

about:
  home: https://github.com/Numerics88/pQCTIO
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'pQCT input/output library'
  description: |
    Input/Output library for reading and writing images for the Stratec pQCT system.
  dev_url: https://github.com/Numerics88/pQCTIO
