package:
  name: pqctio
  version: {{ GIT_DESCRIBE_TAG | lower | replace("v","") }}

source:
  path: ./../../

build:
  number: 0

requirements:
  build:
    - cmake >=3.30.3
    - boost >=1.56
    - ninja
    - gtest
    - {{ compiler('cxx') }}
  host:
    - boost >=1.56

about:
  home: https://github.com/Numerics88/pQCTIO
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'pQCT input/output library'
  description: |
    Input/Output library for reading and writing images for the Stratec pQCT system.
  dev_url: https://github.com/Numerics88/pQCTIO
